package Model;
// Generated Dec 4, 2017 10:13:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PassedTest generated by hbm2java
 */
@Entity
@Table(name="passed_test"
    ,catalog="testsystem"
)
public class PassedTest  implements java.io.Serializable {


     private String id;
     private Test test;
     private User user;
     private double mark;
     private Date testDate;

    public PassedTest() {
    }

    public PassedTest(String id, Test test, User user, double mark, Date testDate) {
       this.id = id;
       this.test = test;
       this.user = user;
       this.mark = mark;
       this.testDate = testDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="test_id", nullable=false)
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="mark", nullable=false)
    public double getMark() {
        return this.mark;
    }
    
    public void setMark(double mark) {
        this.mark = mark;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="test_date", nullable=false, length=19)
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }




}


