package Model;
// Generated Dec 4, 2017 10:13:39 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name="subject"
    ,catalog="testsystem"
)
public class Subject  implements java.io.Serializable {


     private String id;
     private String title;
     private boolean deleted;

    public Subject() {
    }

	
    public Subject(String id, String title) {
        this.id = id;
        this.title = title;
        this.deleted = false;
    }
    
    @Id 
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    @Column(name="title", nullable=false, length=300)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="deleted")
    public boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
}
